# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_card_front'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='front',
        ),
    ]
