# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_card_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='front',
            field=models.CharField(default='front', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='times_reviewed',
            field=models.IntegerField(default=0),
        ),
    ]
