# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='times_reviewed',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
