# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171008_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['review_date']},
        ),
        migrations.RemoveField(
            model_name='card',
            name='last_review',
        ),
        migrations.AddField(
            model_name='card',
            name='back',
            field=models.CharField(default='back', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='answer_quality',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
