# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_review_answer_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='answer_quality',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
