# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_review_answer_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='easiness_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='card',
            name='interval',
            field=models.IntegerField(default=0),
        ),
    ]
